-- =============================================================================
-- TurnoSmart · Esquema base (idempotente)
--
-- Las tablas ya existen en el proyecto (creadas a mano). Esta migración las
-- deja versionadas y completas SIN destruir datos: `create table if not
-- exists` + `add column if not exists` para cada columna que usa la app, y
-- restricciones nuevas como NOT VALID (no revalidan filas existentes).
-- Se puede ejecutar más de una vez.
-- =============================================================================

create extension if not exists pgcrypto;

-- Agrega una restricción solo si todavía no existe (por nombre).
create or replace function pg_temp.agregar_restriccion(p_tabla regclass, p_nombre text, p_definicion text)
returns void language plpgsql as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = p_tabla and conname = p_nombre) then
    execute format('alter table %s add constraint %I %s', p_tabla, p_nombre, p_definicion);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Catálogos
-- ---------------------------------------------------------------------------
create table if not exists public.especialidades (
  id smallint generated by default as identity primary key,
  nombre text not null
);
alter table public.especialidades add column if not exists nombre text;
create unique index if not exists uq_especialidades_nombre on public.especialidades (nombre);

create table if not exists public.consultorios (
  id uuid primary key default gen_random_uuid(),
  nombre text not null
);
alter table public.consultorios add column if not exists nombre text;
alter table public.consultorios add column if not exists direccion text;
alter table public.consultorios add column if not exists ciudad text;
alter table public.consultorios add column if not exists latitud double precision;
alter table public.consultorios add column if not exists longitud double precision;

create table if not exists public.profesionales (
  id uuid primary key default gen_random_uuid(),
  nombre text not null
);
alter table public.profesionales add column if not exists nombre text;
alter table public.profesionales add column if not exists especialidad_id smallint references public.especialidades (id);
alter table public.profesionales add column if not exists consultorio_id uuid references public.consultorios (id);

-- ---------------------------------------------------------------------------
-- Pacientes (ya conectada al perfil; solo se asegura la unicidad de la cédula)
-- ---------------------------------------------------------------------------
create unique index if not exists uq_pacientes_cedula on public.pacientes (cedula);

-- ---------------------------------------------------------------------------
-- Lista de espera
-- ---------------------------------------------------------------------------
alter table public.solicitudes_espera alter column id set default gen_random_uuid();
alter table public.solicitudes_espera alter column estado set default 'activa';
alter table public.solicitudes_espera alter column creada_en set default now();
select pg_temp.agregar_restriccion('public.solicitudes_espera', 'solicitudes_espera_estado_check',
  $$check (estado in ('activa', 'retirada', 'atendida')) not valid$$);
select pg_temp.agregar_restriccion('public.solicitudes_espera', 'solicitudes_espera_paciente_fk',
  'foreign key (paciente_id) references public.pacientes (id) on delete cascade not valid');
select pg_temp.agregar_restriccion('public.solicitudes_espera', 'solicitudes_espera_especialidad_fk',
  'foreign key (especialidad_id) references public.especialidades (id) not valid');
create unique index if not exists uq_solicitud_espera_activa
  on public.solicitudes_espera (paciente_id, especialidad_id) where estado = 'activa';
create index if not exists idx_solicitudes_espera_cola
  on public.solicitudes_espera (especialidad_id, estado, creada_en);

-- ---------------------------------------------------------------------------
-- Citas
-- ---------------------------------------------------------------------------
create table if not exists public.citas (
  id uuid primary key default gen_random_uuid()
);
alter table public.citas add column if not exists paciente_id uuid references public.pacientes (id) on delete cascade;
alter table public.citas add column if not exists especialidad_id smallint references public.especialidades (id);
alter table public.citas add column if not exists profesional_id uuid references public.profesionales (id);
alter table public.citas add column if not exists consultorio_id uuid references public.consultorios (id);
alter table public.citas add column if not exists fecha_hora timestamptz;
alter table public.citas add column if not exists estado text not null default 'confirmada';
alter table public.citas add column if not exists origen text not null default 'reserva-directa';
alter table public.citas add column if not exists oferta_id uuid;
alter table public.citas add column if not exists creada_en timestamptz not null default now();
alter table public.citas add column if not exists cancelada_en timestamptz;
select pg_temp.agregar_restriccion('public.citas', 'citas_estado_check',
  $$check (estado in ('confirmada', 'asistida', 'cancelada', 'reasignada', 'no-show')) not valid$$);
select pg_temp.agregar_restriccion('public.citas', 'citas_origen_check',
  $$check (origen in ('reserva-directa', 'cupo-recuperado')) not valid$$);
create index if not exists idx_citas_paciente_fecha on public.citas (paciente_id, fecha_hora);

-- ---------------------------------------------------------------------------
-- Cupos: espacio liberado por una cancelación, inasistencia u otro motivo
-- ---------------------------------------------------------------------------
create table if not exists public.cupos (
  id uuid primary key default gen_random_uuid()
);
alter table public.cupos add column if not exists cita_origen_id uuid references public.citas (id) on delete set null;
alter table public.cupos add column if not exists especialidad_id smallint references public.especialidades (id);
alter table public.cupos add column if not exists profesional_id uuid references public.profesionales (id);
alter table public.cupos add column if not exists consultorio_id uuid references public.consultorios (id);
alter table public.cupos add column if not exists fecha_hora timestamptz;
alter table public.cupos add column if not exists motivo text not null default 'cancelacion';
alter table public.cupos add column if not exists estado text not null default 'abierto';
alter table public.cupos add column if not exists creado_en timestamptz not null default now();
select pg_temp.agregar_restriccion('public.cupos', 'cupos_estado_check',
  $$check (estado in ('abierto', 'ofrecido', 'tomado', 'expirado')) not valid$$);
select pg_temp.agregar_restriccion('public.cupos', 'cupos_motivo_check',
  $$check (motivo in ('cancelacion', 'inasistencia', 'otro')) not valid$$);
-- Una cita origen genera como máximo un cupo.
create unique index if not exists uq_cupos_cita_origen on public.cupos (cita_origen_id) where cita_origen_id is not null;
create index if not exists idx_cupos_estado on public.cupos (estado, fecha_hora);

-- ---------------------------------------------------------------------------
-- Ofertas de cupo
-- ---------------------------------------------------------------------------
create table if not exists public.ofertas (
  id uuid primary key default gen_random_uuid()
);
alter table public.ofertas add column if not exists cupo_id uuid references public.cupos (id) on delete cascade;
alter table public.ofertas add column if not exists paciente_id uuid references public.pacientes (id) on delete cascade;
alter table public.ofertas add column if not exists estado text not null default 'pendiente';
-- Score interno de la priorización (0-1). Nunca se muestra al paciente.
alter table public.ofertas add column if not exists score numeric;
alter table public.ofertas add column if not exists expira_en timestamptz;
alter table public.ofertas add column if not exists creada_en timestamptz not null default now();
alter table public.ofertas add column if not exists respondida_en timestamptz;
select pg_temp.agregar_restriccion('public.ofertas', 'ofertas_estado_check',
  $$check (estado in ('pendiente', 'aceptada', 'rechazada', 'expirada')) not valid$$);
-- Como máximo una oferta aceptada, y una pendiente a la vez, por cupo.
create unique index if not exists uq_oferta_aceptada_por_cupo on public.ofertas (cupo_id) where estado = 'aceptada';
create unique index if not exists uq_oferta_pendiente_por_cupo on public.ofertas (cupo_id) where estado = 'pendiente';
-- Un mismo cupo no se le ofrece dos veces al mismo paciente.
create unique index if not exists uq_oferta_cupo_paciente on public.ofertas (cupo_id, paciente_id);
create index if not exists idx_ofertas_paciente_estado on public.ofertas (paciente_id, estado, expira_en);

select pg_temp.agregar_restriccion('public.citas', 'citas_oferta_fk',
  'foreign key (oferta_id) references public.ofertas (id) on delete set null not valid');

-- Factores de la explicación (máximo 4 visibles por oferta).
create table if not exists public.ofertas_factores (
  id uuid primary key default gen_random_uuid()
);
alter table public.ofertas_factores add column if not exists oferta_id uuid references public.ofertas (id) on delete cascade;
alter table public.ofertas_factores add column if not exists clave text;
alter table public.ofertas_factores add column if not exists etiqueta text;
alter table public.ofertas_factores add column if not exists valor text;
alter table public.ofertas_factores add column if not exists valor_numerico numeric;
alter table public.ofertas_factores add column if not exists peso numeric;
alter table public.ofertas_factores add column if not exists orden smallint;
select pg_temp.agregar_restriccion('public.ofertas_factores', 'ofertas_factores_clave_check',
  $$check (clave in ('tiempo-espera', 'especialidad', 'horario', 'distancia', 'disponibilidad', 'compatibilidad')) not valid$$);
select pg_temp.agregar_restriccion('public.ofertas_factores', 'ofertas_factores_peso_check',
  'check (peso >= 0 and peso <= 1) not valid');
select pg_temp.agregar_restriccion('public.ofertas_factores', 'ofertas_factores_orden_check',
  'check (orden between 1 and 4) not valid');
create unique index if not exists uq_ofertas_factores_orden on public.ofertas_factores (oferta_id, orden);
create unique index if not exists uq_ofertas_factores_clave on public.ofertas_factores (oferta_id, clave);

-- Historial de la oferta; cada evento se registra una sola vez.
create table if not exists public.ofertas_eventos (
  id uuid primary key default gen_random_uuid()
);
alter table public.ofertas_eventos add column if not exists oferta_id uuid references public.ofertas (id) on delete cascade;
alter table public.ofertas_eventos add column if not exists tipo text;
alter table public.ofertas_eventos add column if not exists creado_en timestamptz not null default now();
select pg_temp.agregar_restriccion('public.ofertas_eventos', 'ofertas_eventos_tipo_check',
  $$check (tipo in ('enviada', 'vista', 'aceptada', 'rechazada', 'expirada')) not valid$$);
create unique index if not exists uq_ofertas_eventos_tipo on public.ofertas_eventos (oferta_id, tipo);

-- ---------------------------------------------------------------------------
-- Notificaciones: el tipo y los datos; el texto lo redacta la app en su idioma.
-- ---------------------------------------------------------------------------
create table if not exists public.notificaciones (
  id uuid primary key default gen_random_uuid()
);
alter table public.notificaciones add column if not exists paciente_id uuid references public.pacientes (id) on delete cascade;
alter table public.notificaciones add column if not exists tipo text;
alter table public.notificaciones add column if not exists datos jsonb not null default '{}'::jsonb;
alter table public.notificaciones add column if not exists referencia_id uuid;
alter table public.notificaciones add column if not exists leida boolean not null default false;
alter table public.notificaciones add column if not exists creada_en timestamptz not null default now();
alter table public.notificaciones add column if not exists leida_en timestamptz;
select pg_temp.agregar_restriccion('public.notificaciones', 'notificaciones_tipo_check',
  $$check (tipo in ('cupo-ultimo-minuto', 'recordatorio', 'confirmacion', 'expiracion')) not valid$$);
create index if not exists idx_notificaciones_paciente on public.notificaciones (paciente_id, creada_en desc);
